/**
 * TypeScript Type Definitions for FlirtDeck
 * 
 * BIG PICTURE:
 * This file defines the "shape" of our data - like a blueprint for objects.
 * TypeScript uses these to catch errors before runtime (e.g., typo in property name).
 * 
 * Think of it like a contract: "A User MUST have these fields with these types"
 * 
 * WHY WE NEED THIS:
 * - Autocomplete in VS Code (type user. and see all properties)
 * - Catch bugs early (can't assign string to number field)
 * - Self-documenting code (anyone can see what a User looks like)
 */

// ============================================
// USER TYPES
// ============================================

/**
 * User Type - Represents an authenticated user in our system
 * 
 * This matches what our backend returns from GET /auth/me
 * 
 * Example:
 * {
 *   user_id: "abc123",
 *   email: "john@example.com",
 *   name: "John Doe",
 *   subscription_status: "premium",
 *   created_at: "2024-01-15T10:30:00Z"
 * }
 */
export interface User {
  user_id: string;              // Unique ID from Cognito (the "sub" claim)
  email: string;                // User's email address
  name?: string;                // Optional: User's display name (from Google)
  subscription_status: 'free' | 'premium';  // Billing tier (limits what they can do)
  created_at?: string;          // ISO timestamp when account was created
  updated_at?: string;          // ISO timestamp when profile was last updated
}

// ============================================
// QUESTION TYPES
// ============================================

/**
 * Question Type - Represents a conversation starter
 * 
 * Questions are hardcoded in our backend (250 total).
 * They're categorized to help users find the right vibe.
 * 
 * Example:
 * {
 *   id: "q001",
 *   text: "If you could have dinner with anyone, who would it be?",
 *   category: "life"
 * }
 */
export interface Question {
  id: string;                   // Unique identifier (e.g., "q001", "q042")
  text: string;                 // The actual question text
  category: QuestionCategory;   // Which bucket it falls into
}

/**
 * Question Categories - The four types of conversation starters
 
 */
export type QuestionCategory = 'life' | 'random' | 'deep' | 'experiences';

// ============================================
// CONNECTION TYPES
// ============================================

/**
 * Connection Type - Represents someone the user is talking to
 * 
 * IMPORTANT: A "connection" is NOT a user account in our system!
 * It's just a name/label the user gives (e.g., "Sarah from Hinge").
 * 
 * This is how we organize question usage - each connection has its own history.
 * 
 * Example:
 * {
 *   connection_id: "conn_123",
 *   name: "Sarah from Hinge",
 *   created_at: "2024-01-15T10:30:00Z"
 * }
 */
export interface Connection {
  connection_id: string;        // Unique ID (UUID generated by backend)
  name: string;                 // User-provided label (e.g., "Mike from work")
  created_at: string;           // When this connection was created
  user_id?: string;             // Optional: Which user owns this connection
}

/**
 * CreateConnectionInput - Data needed to create a new connection
 * 
 * This is what the frontend sends to POST /connections
 */
export interface CreateConnectionInput {
  name: string;                 // The only required field - just a name!
}

// ============================================
// USAGE TYPES
// ============================================

/**
 * QuestionUsage Type - Tracks when a user uses a question with a connection
 * 
 * BIG PICTURE:
 * This is the core of the app's value! It logs:
 * - What question was asked
 * - To whom (which connection)
 * - What happened (their response, your response)
 * 
 * This builds a history so users can reference past conversations.
 * 
 * Example:
 * {
 *   usage_id: "usage_789",
 *   user_id: "abc123",
 *   connection_id: "conn_456",
 *   question_id: "q042",
 *   question_text: "What's your dream vacation?",
 *   their_response: "Backpacking through Japan!",
 *   my_response: "That sounds amazing! I've always wanted to visit Kyoto.",
 *   used_at: "2024-01-15T14:30:00Z"
 * }
 */
export interface QuestionUsage {
  usage_id: string;             // Unique ID for this usage record
  user_id: string;              // Who used the question
  connection_id: string;        // With which connection
  question_id: string;          // Which question (reference to Question.id)
  question_text: string;        // Copy of the question (for display, avoids extra lookup)
  their_response?: string;      // Optional: What the other person said
  my_response?: string;         // Optional: What the user replied
  notes?: string;               // Optional: Any additional context
  used_at: string;              // ISO timestamp when question was used
}

/**
 * CreateUsageInput - Data needed to log question usage
 * 
 * This is what the frontend sends to POST /usage
 */
export interface CreateUsageInput {
  connection_id: string;        // Which connection this is for
  question_id: string;          // Which question was used
  their_response?: string;      // Optional: Log immediately or add later
  my_response?: string;         // Optional: Log immediately or add later
  notes?: string;               // Optional: Any context
}

/**
 * UpdateUsageInput - Data to update an existing usage record
 * 
 * Allows users to add responses after the fact:
 * "Oh yeah, she said X and I replied Y"
 */
export interface UpdateUsageInput {
  their_response?: string;
  my_response?: string;
  notes?: string;
}

// ============================================
// AUTH TYPES
// ============================================

/**
 * AuthTokens - OAuth tokens from Cognito
 * 
 * BIG PICTURE:
 * After Google OAuth login, Cognito gives us these tokens.
 * We store them in localStorage and include them in API requests.
 * 
 * - idToken: Contains user info (email, name, etc.) - used for authentication
 * - accessToken: Used to call Cognito APIs (we don't really use this much)
 * - refreshToken: Used to get new tokens when they expire (1 hour lifespan)
 */
export interface AuthTokens {
  idToken: string;              // JWT with user claims - this is what we send to our API
  accessToken: string;          // OAuth access token
  refreshToken: string;         // Used to get new tokens without re-login
}

/**
 * AuthContextType - Shape of our Auth Context
 * 
 * This defines what the useAuth() hook will return.
 * See AuthContext.tsx for the implementation.
 */
export interface AuthContextType {
  user: User | null;            // Current logged-in user (null if not logged in)
  loading: boolean;             // True while checking authentication status
  login: () => void;            // Function to redirect to Google OAuth
  logout: () => void;           // Function to clear session and logout
  isAuthenticated: boolean;     // Computed: true if user exists
}

// ============================================
// API TYPES
// ============================================

/**
 * ApiError - Standard error response from our backend
 * 
 * All Lambda errors return this shape (see backend/shared/responses.py)
 * 
 * Example:
 * {
 *   error: "Missing user ID in token",
 *   code: "INVALID_TOKEN"
 * }
 */
export interface ApiError {
  error: string;                // Human-readable error message
  code?: string;                // Optional: Machine-readable error code
}

/**
 * PaginatedResponse - For endpoints that return lists with pagination
 * 
 * Not used yet, but good to have for future features
 * (e.g., if user has 1000 usage records, don't load all at once)
 */
export interface PaginatedResponse<T> {
  items: T[];                   // Array of whatever type (User, Connection, etc.)
  next_token?: string;          // If present, there are more results
  count: number;                // Total number of items in this page
}

// ============================================
// STRIPE TYPES (for later phases)
// ============================================

/**
 * CheckoutSession - Stripe checkout information
 * 
 * Used when user clicks "Upgrade to Premium"
 * Backend creates a Stripe checkout session and returns this URL
 */
export interface CheckoutSession {
  checkout_url: string;         // Stripe-hosted checkout page URL
  session_id: string;           // Stripe session ID (for tracking)
}

/**
 * Subscription - User's subscription details
 * 
 * Returned from GET /billing/status
 */
export interface Subscription {
  status: 'free' | 'premium' | 'cancelled';
  current_period_end?: string;  // When current billing period ends (ISO date)
  cancel_at_period_end?: boolean; // True if user cancelled but still has access
}

